apiVersion: v1
kind: Service
metadata:
  name: cesae-contacts-api-service
spec:
  selector:
    project: cesae-contacts-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
