apiVersion: v1
kind: Service
metadata:
  name: cesae-contacts-api-service
  namespace: default
  labels:
    version: v1
spec:
  selector:
    project: cesae-contacts-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
