name: Issue triage
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Issue aberta - Atribuição de label
        id: label
        run: |
          if [[ "${{ github.event.issue.body }}" == *"bug"* ]]; then
            echo "labels=bug" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.issue.body }}" == *"funcionalidade"* ]]; then
            echo "labels=enhancement" >> $GITHUB_OUTPUT
          else
            echo "labels=question" >> $GITHUB_OUTPUT
          fi

      - name: Aplicar labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = process.env.LABELS
            if (labels) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [labels]
              })
            }
        env:
          LABELS: ${{ steps.label.outputs.labels }}

      - name: Auto atribuir issue
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.payload.sender.login]
            })

      - name: Comentário automático
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueType = process.env.LABELS === 'bug' ? 'bug' :
                             process.env.LABELS === 'enhancement' ? 'funcionalidade' : 'questão'

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Obrigado por reportar ${issueType === 'bug' ? 'este' : 'esta'} ${issueType}! Vamos analisar o mais breve possível.`
            })
        env:
          LABELS: ${{ steps.label.outputs.labels }}
